### ISSUE TITLE
Recent release causing errors in 'Build' stage

### ISSUE THREAD

**Issue by jcohen120** [christianhelle/apiclientcodegen#437]
Hello, 

Unfortunately, the recent update of this extension - v 1.5.72 - is completely causing the build of my .NET Core v3.0 REST Web API project to fail. I am encountering the following errors and I can't seem to resolve them. 

I did notice that 8 days ago, there was a release for the openapi-generator project - v6.2.1. One of the issues was fixing the data type for "maps of maps". I have a feeling that it's related to the issues that I am now experiencing. Based on the image I attached, I'm wondering if anyone can offer any insight as to why I may be experiencing this issue. I've had absolutely no luck in troubleshooting on my own. 

Any help would be greatly appreciated. 

Thank you. 

![image](https://user-images.githubusercontent.com/49422317/200720802-c4201bdd-6cd7-421d-9b84-509f95a45c1c.png)

**Comment by christianhelle** [comment]
Thanks for reporting @jcohen120

I'm pretty sure that this is due to OpenAPI Generator v6.2.1. Do you remember what was the latest working version of the extension that worked for you? 

Would it be possible for you to share the Swagger file? It would help me for troubleshooting

**Comment by christianhelle** [comment]
@jcohen120 I played a bit with the attached Swagger file. I can't for sure say what's wrong but it seems that the `ProviderTechList` causes OpenAPI Generator to fail. Renaming this to something like `ProviderTechCollection` or `ProviderTechEntries` fixes the code generation issue. I'm again not sure about what's wrong in OpenAPI Generator, but it sure seems like some string matching code depends on the word `List` and has some consequences

I can also see that the Swagger file doesn't work (as it is) with OpenAPI Generator v6.2.0 either. I unfortunately can't go any lower than v6.2.0 for OpenAPI Generator as older versions of RestSharp, a dependency of OpenAPI Generator generated code has some security issues and v6.2.0 (and higher) is compatible with the latest versions of RestSharp, where these security issues have been fixed

I of course don't really know about what domain or problem your system is trying to solve, but if its not too much work for you then renaming `ProviderTechList` to `ProviderTechCollection` or something similar will resolve the code generation issue. 

By the way, the Swagger file you attached also works (as it is) with NSwag, but I guess that's a bigger change for you since you have to update all usages of the generated code.

**Comment by christianhelle** [comment]
@jcohen120 I recently removed support for .NET versions that are out-of-support. From December 2022, only .NET Core 6 (and higher) will be supported by Microsoft.

You might want to consider upgrading your API to run on .NET 6 (LTS) or .NET 7 (Recommended)

**Comment by jcohen120** [comment]
@christianhelle There we go... I have another API project that uses .NET Core v3.1, which is technically still in support and I experienced no issues there with respect to the build process... however, the API currently experiencing the issue is built on top of .NET Core v3.0, which is out of support. I actually have a project to upgrade it before end of year, which clearly needs to be accelerated. 

I'm going to proceed with updating the version of the APIs to .NET Core 6 to see if that resolves the issue. 

This insight has been super helpful, thank you! You can feel free to close the issue as it seems pretty clear that the old unsupported version is the source of the problem.

**Comment by christianhelle** [comment]
> This insight has been super helpful, thank you! You can feel free to close the issue as it seems pretty clear that the old unsupported version is the source of the problem.

@jcohen120  Unfortunately, the model `ProviderTechList`  also had problems in .NET 6.0 and .NET 7.0. But renaming it something that doesn't end with `List` solved the "problem"

I'll close this for now as there is not really much I can do from my side, since its OpenAPI Generator itself that seems to be the problem

**Comment by jcohen120** [comment]
Thanks @christianhelle I did see that I kept having issues with that object, but didn't know that was the reason. Thank you! 

I'm going to change that name. 

By the way, is the extension currently working for apps running on .NET Core v3.1 until December 13th? That's when LTS is going to end for that version. Or is it only working for .NET 6 and 7 as of now? 

Thanks again.

**Comment by christianhelle** [comment]
@jcohen120 I'm not actually removing support directly, instead I'm removing tests that verify against non-supported versions. 

I have a rather comprehensive set of regression tests that generates code for the Swagger Petstore v2 and v3 example spec using NSwag, OpenAPI Generator, AutoRest, and Seagger codegen CLI. The generated C# code will be tested by building it in the "supported" versions of .NET. I do these sets of tests using different combinations of Operating systems and NodeJS/NPM versions

**Comment by jcohen120** [comment]
That makes perfect sense, thank you!

I appreciate all your help.
