### ISSUE TITLE
support for Visual Studio for Mac ?

### ISSUE THREAD

**Issue by robbiemu** [christianhelle/apiclientcodegen#76]
is Visual Studio for Mac supported? If so, how do we install this?

**Comment by christianhelle** [comment]
First of all, thanks for reaching out! I really appreciate input like this

Currently, the Visual Studio Extension only fully supports Visual Studio 2019 and 2017. 

Unfortunately, Visual Studio for Mac is a completely different system and the Visual Studio extensibility API's that I depend on are not all compatible with Visual Studio for Mac (which is really just a re-branding of Xamarin Studio). For now, I use command line tools to re-generate the REST API Client code. I'm a Xamarin developer in my day job and I do understand the lack of support with the tool.

I also do want you to know that I have plans on building IDE integration for Visual Studio for Mac and JetBrains Rider. I'm on a Mac 8 hours a day and I really miss some IDE integrations in Mac tooling in general

Because the extensibility API's in Visual Studio for Mac are so very different from Visual Studio on Windows I will probably take a different approach that to use a code-behind file generate by a `IVSingleFileGenerator` implementation. For now my plan is to piggy back on my CLI tool called **rapicgen** and make calls to that and add the resulting file to the C# project. I haven't thought everything through in detail yet

**Comment by christianhelle** [comment]
You can check out the instructions on how to use the CLI tool in the [README](https://github.com/christianhelle/apiclientcodegen#cross-platform-command-line-tool)

**Comment by christianhelle** [comment]
I started looking into this in detail over the weekend and the MonoDevelop documentation is quite good. Hopefully I'll get more progress throughout the week

Progress can be tracked via my commits in the [vs-for-mac branch](
https://github.com/christianhelle/apiclientcodegen/commits/vs-for-mac)

**Comment by christianhelle** [comment]
Figured out how to add custom commands to the Projects pad

![](https://github.com/christianhelle/apiclientcodegen/blob/vs-for-mac/images/vsmac-add-new-menu.png?raw=true)

**Comment by christianhelle** [comment]
So, the Add-in repository for Visual Studio for Mac is currently not allowing new accounts, this is a bit of a problem for publishing this extension. For now, I will just include it the Github Releases and will add a link to the mpack file
