### ISSUE TITLE
Visual Studio freezes when generating client api 

### ISSUE THREAD

**Issue by brandonvmoore** [christianhelle/apiclientcodegen#776]
When saving the yaml file in a .NET 6 Class Library, Visual Studio freezes while the generator runs. Other applications in the solution are Azure Functions

Previously I experienced long wait times for the generator to complete, and it is possible that if I left it long enough maybe it would finish. I have let it run for at least 10 minutes, if not longer.

**Support Key**: a5b90b7

**To Reproduce**
1. Make any change to the yaml file.
2. Save the change.
3. Visual Studio freezes and must be closed from the Task Manager

Expected behavior
When I update the yaml file, I expect it to regenerate the C# classes to match the updates I made within a reasonable period of time.

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.6

Additional comments:

I had this issue in the past, but it went away after I converted an enum with a lot of values (like a hundred or more) to a simple integer field and just put the possible values in the description text. The issue has reappeared now that I've added a callback section for two end points. This callback section is identical to the callback section that already existed for 2 other end endpoints.

I apologize for not posting the yaml file yet as I want to get permission first as I don't know if I'd be breaking any company rules. If I'm not able to post the actual file, I will see if I can create a modified version to share. Stay tuned...

I've attached an image of other installed extensions. I didn't even realize some of these were here and plan to remove some of them, so I will give an update if this helps but I doubt any of these would be an issue.

![image](https://github.com/christianhelle/apiclientcodegen/assets/967883/c7d10ea2-3570-4a1c-90d0-39488af02c5f)

**Comment by christianhelle** [comment]
@brandonvmoore Thanks for taking the time to report this

I have been testing the extension lately with a large OpenAPI spec file that one of my users recently shared with me -> https://developer.allegro.pl/swagger.yaml. It's around 1MB in size with 28k lines of code.

When I generate code using NSwag v14.0.2, it takes around 6 to 7 seconds. During this time, Visual Studio is pretty much locked. This is due to the fact that the COM interfaces that you need to implement for building custom tool generators run synchronously.

```
2/1/2024 9:53:37 PM: Checking required dependencies
2/1/2024 9:53:37 PM: Installing Newtonsoft.Json version 13.0.3
2/1/2024 9:53:38 PM: Successfully installed Newtonsoft.Json version 13.0.3
2/1/2024 9:53:43 PM: Output file size: 4167840
```

with Refitter v0.9.6, it takes around the same time. This is most likely because Refitter uses NSwag to parse the OpenAPI spec and to generate contracts. For Refitter, I get the following output

```
2/1/2024 10:34:19 PM: Generating code using Refitter
2/1/2024 10:34:19 PM: Checking required dependencies
2/1/2024 10:34:19 PM: Refit is already installed
2/1/2024 10:34:25 PM: Output file size: 1452558
```

OpenAPI Generator v7.2.0 was the slowest and Visual Studio was **completely unusable** for a good 2 minutes

```
2/1/2024 10:37:30 PM: Generating code using OpenApi
....
2/1/2024 10:37:32 PM: Checking Java version
2/1/2024 10:37:32 PM: Executing:
2/1/2024 10:37:32 PM: C:\Program Files\Microsoft\jdk-17.0.4.101-hotspot\bin\java.exe -version
2/1/2024 10:37:32 PM: 
2/1/2024 10:37:32 PM: openjdk version "17.0.4.1" 2022-08-12 LTS
2/1/2024 10:37:32 PM: OpenJDK Runtime Environment Microsoft-40354 (build 17.0.4.1+1-LTS)
2/1/2024 10:37:32 PM: OpenJDK 64-Bit Server VM Microsoft-40354 (build 17.0.4.1+1-LTS, mixed mode, sharing)
2/1/2024 10:37:32 PM: 
2/1/2024 10:37:32 PM: Executing:
2/1/2024 10:37:32 PM: C:\Program Files\Microsoft\jdk-17.0.4.101-hotspot\bin\java.exe -jar "C:\Users\christian\AppData\Local\Temp\openapi-generator-cli.jar" generate --generator-name csharp --input-spec "Swagger.yaml" --output "C:\Users\christian\AppData\Local\Temp\981c86189ff142cba01e453cacf7d2b5\TempApiClient" --package-name "ConsoleApp76" --global-property apiTests=false --global-property modelTests=false --global-property skipFormModel=True --skip-overwrite --additional-properties optionalEmitDefaultValues=True --additional-properties optionalMethodArguments=True --additional-properties generatePropertyChanged=False --additional-properties useCollection=False --additional-properties useDateTimeOffset=False --additional-properties targetFramework=netstandard2.1 
....
2/1/2024 10:39:32 PM: Output file size: 8739854
```

Microsoft Kiota v1.10.1 fails to generate code for this large OpenAPI spec

I'm currently testing all this on Visual Studio 2022 Enterprise 64-bit (v17.9.0 Preview 2.0) from Windows 10 running on a 6-year-old 32-core workstation with 128 GB of RAM and an M.2 NVMe drive. It's not the latest nor the greatest, but it's not slow either

**Comment by brandonvmoore** [comment]
I did not initially think to see if other extensions could be the issue because the only ones I had personally installed were for SQL Server and Terraform, but I didn't realize there were about 7 others apparently included from when I installed Visual Studio. I also didn't think this was the problem due to the fact it previously worked under the same circumstances.

After I disabled all the other extensions it did start working as expected, and was much, much faster. I suspect other extensions were bogging it down big time even when it did work before. So thank you for pointing that issue out in your original response as I believe it resolves the issue.

**Comment by christianhelle** [comment]
@brandonvmoore If you feel that we resolved your issue then I would be very grateful for an updated rating or review on the [Visual Studio Marketplace](https://bit.ly/rapicgen-vs2022) 😄 

Of course, If you mean that the extension deserves its current rating due to its current feature set and how it currently works for you then let's keep it as it is, but, I would love to know more about what you think it lacks
