### ISSUE TITLE
Implement a Refitter Settings File as part of generation process

### ISSUE THREAD

**Issue by dammitjanet** [christianhelle/apiclientcodegen#845]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently the Refitter implementation within the REST API Generator only implements 7 or 8 of the 15/16 different settings that can be used. Supplying a settings file as part of the integration would allow for easier integration and development.

If a settings file exists, then Regenerating would use the Settings and not the Configuration
If a settings file does not exist, then one should be output as part of the generation process. This could be turned on/off in the configuration panel as an option.

Since the Refitter process doesn't log which options were used in the console, this could be a handy way to:

1. Provide an easier way to configure Refitter when options are not present in the Extension Options configuration pane such as now and if new options are added to Refitter in the future
2. Provide a way for settings to be consistent across teams (with the settings file in source control)

**Describe alternatives you've considered**

Add more of the configuration settings to Refitter configuration panel

**Additional context**

The obvious workaround is to installer Refitter and use Package Manage console to do all of this manually, but that just means that you don't use the great tool you've created

**Comment by christianhelle** [comment]
Thanks for taking the time to request this @dammitjanet 

This is something I already started working on but my pace is a bit slow

Since I'm also the author of Refitter, I would like to have as much support for it in this tool

**Comment by christianhelle** [comment]
@dammitjanet it took a while to find time but I have been working on this feature today. I built it in a way that when generating using Refitter, it generates a .refitter file (with default values) beside the OpenAPI spec file, this only happens if the .refitter doesn't already exist. 

I added a context menu for .refitter files that looks like this:

![image](https://github.com/christianhelle/apiclientcodegen/assets/710400/6cf41743-c40f-4edd-b375-cf4994c24320)

So its possible to just add a .refitter file to the project and generate code using it
