### ISSUE TITLE
Support Authorization HTTP request header

### ISSUE THREAD

**Issue by ChrisVance** [christianhelle/apiclientcodegen#86]
Our company uses a hosted GitHub Enterprise instance. We require a personal access token in order to view the openapi API yaml. In addition, the API itself has $ref references to URIs within the same hosted GitHub instance. If a token is not provided, a 404 response is returned.

While I can send the token via a query string in the New REST API Client (e.g. path/to/api.yaml?token=abc123), the API file itself doesn't hardcode a token in their references (which would represent a security lapse). As a result, the client generation fails because the reference requests result in a 404 Not Found.

GitHub Enterprise supports sending these Personal Access Tokens via the Authorization HTTP request header, e.g.

`Authorization: token abc123`

Can you consider implementing use of an Authorization header? Our API documents come from a single subdomain, e.g. github.company.com, but other users might have different usage scenarios. I'm not sure you'd want to store the access token, from a data security standpoint. Maybe prompt for each overall request?

**Comment by christianhelle** [comment]
Hi @ChrisVance 

First of all, thanks for bringing this up. I would love to implement something to help. 

What I can quickly do is to add an input field in the "Add New REST API Client" dialog for adding custom headers to attach to the HTTP request. This would at least provide an immediate fix for adding new code generated API Clients.

For a direct work around, you can download the Open API spec document (in JSON) manually then add it to the project, right click on it, then select the code generator you want to use from the REST API Client Generator menu

As shown here:
![](https://github.com/christianhelle/apiclientcodegen/raw/master/images/solution-explorer-context-menu.jpg)

This will set a custom tool on the project item and will automagically re-generate the API client when file changes occur on the Open API spec JSON file

Currently, I only support JSON files as that's the way me and my team uses the tool for projects I'm directly involved in. I'll look into adding support for YAML files, It's a bit complicated but because I want the implementation to be aligned across the code generators I use behind the scenes. I pretty much just piggy back on top of 3rd party tools such as AutoRest, NSwag, Swagger codegen, and OpenAPI Generator.
